导入pandas和numpy库

In [1]:
import pandas as pd
import numpy as np

## 一.获得DataFrame的两种方式

### 1.自己创建DataFrame

（1）通过字典创建DataFrame

+ 通过单层字典创建

In [6]:
df1 = pd.DataFrame({"a":range(100,111),"b":range(200,211)})
df1

      a    b
0   100  200
1   101  201
2   102  202
3   103  203
4   104  204
5   105  205
6   106  206
7   107  207
8   108  208
9   109  209
10  110  210

+ 通过嵌套字典创建DataFrame

In [9]:
dict_1 = {"b":{2015:3,2017:7,2016:4},"a":{2015:10,2017:27,2016:20}}
df2 = pd.DataFrame(dict_1)
df2

       a  b
2015  10  3
2016  20  4
2017  27  7

显式地去指定索引和列名的顺序

In [10]:
dict_1 = {"a":{2016:4,2015:3,2017:7},"b":{2017:27,2016:20,2015:10}}
df2 = pd.DataFrame(dict_1,index=[2017,2015,2016],columns=["b","a"])
df2

       b  a
2017  27  7
2015  10  3
2016  20  4

（2）通过数组创建DataFrame

In [11]:
df3 = pd.DataFrame(np.arange(12).reshape(3,4),index=[2015,2016,2017],columns=["产品1","产品2","产品3","产品4"])
df3

      产品1  产品2  产品3  产品4
2015    0    1    2    3
2016    4    5    6    7
2017    8    9   10   11

### 2.从外部导入DataFrame

导入csv文件

如果导入无中文的文件,输入文件名称即可

In [20]:
cd C:\\Users\\Alienware

C:\Users\Alienware

In [22]:
df1 = pd.read_csv("1.csv")
df1

  name   class  grade
0     a      1     80
1     b      2     90
2     c      1     85
3     d      3     75
4     e      2     60
5     f      1     95

如果导入含中文的csv文件，windows系统下需要添加参数encoding="gbk"

In [8]:
df2 = pd.read_csv("pokemon_data.csv",encoding="gbk")
df2

                            姓名       类型1     类型2   总计  生命值  攻击力  防御力   速度  时代
0                    Bulbasaur     Grass  Poison  318   45   49   49   45   1
1                      Ivysaur     Grass  Poison  405   60   62   63   60   1
2                     Venusaur     Grass  Poison  525   80   82   83   80   1
3        VenusaurMega Venusaur     Grass  Poison  625   80  100  123   80   1
4                   Charmander      Fire     NaN  309   39   52   43   65   1
5                   Charmeleon      Fire     NaN  405   58   64   58   80   1
6                    Charizard      Fire  Flying  534   78   84   78  100   1
7    CharizardMega Charizard X      Fire  Dragon  634   78  130  111  100   1
8    CharizardMega Charizard Y      Fire  Flying  634   78  104   78  100   1
9                     Squirtle     Water     NaN  314   44   48   65   43   1
10                   Wartortle     Water     NaN  405   59   63   80   58   1
11                   Blastoise     Water     NaN  530   79   83  100   78   1
12     BlastoiseMega Blastoise     Water     NaN  630   79  103  120   78   1
13                    Caterpie       Bug     NaN  195   45   30   35   45   1
14                     Metapod       Bug     NaN  205   50   20   55   30   1
15                  Butterfree       Bug  Flying  395   60   45   50   70   1
16                      Weedle       Bug  Poison  195   40   35   30   50   1
17                      Kakuna       Bug  Poison  205   45   25   50   35   1
18                    Beedrill       Bug  Poison  395   65   90   40   75   1
19       BeedrillMega Beedrill       Bug  Poison  495   65  150   40  145   1
20                      Pidgey    Normal  Flying  251   40   45   40   56   1
21                   Pidgeotto    Normal  Flying  349   63   60   55   71   1
22                     Pidgeot    Normal  Flying  479   83   80   75  101   1
23         PidgeotMega Pidgeot    Normal  Flying  579   83   80   80  121   1
24                     Rattata    Normal     NaN  253   30   56   35   72   1
25                    Raticate    Normal     NaN  413   55   81   60   97   1
26                     Spearow    Normal  Flying  262   40   60   30   70   1
27                      Fearow    Normal  Flying  442   65   90   65  100   1
28                       Ekans    Poison     NaN  288   35   60   44   55   1
29                       Arbok    Poison     NaN  438   60   85   69   80   1
..                         ...       ...     ...  ...  ...  ...  ...  ...  ..
770                    Sylveon     Fairy     NaN  525   95   65   65   60   6
771                   Hawlucha  Fighting  Flying  500   78   92   75  118   6
772                    Dedenne  Electric   Fairy  431   67   58   57  101   6
773                    Carbink      Rock   Fairy  500   50   50  150   50   6
774                      Goomy    Dragon     NaN  300   45   50   35   40   6
775                    Sliggoo    Dragon     NaN  452   68   75   53   60   6
776                     Goodra    Dragon     NaN  600   90  100   70   80   6
777                     Klefki     Steel   Fairy  470   57   80   91   75   6
778                   Phantump     Ghost   Grass  309   43   70   48   38   6
779                  Trevenant     Ghost   Grass  474   85  110   76   56   6
780      PumpkabooAverage Size     Ghost   Grass  335   49   66   70   51   6
781        PumpkabooSmall Size     Ghost   Grass  335   44   66   70   56   6
782        PumpkabooLarge Size     Ghost   Grass  335   54   66   70   46   6
783        PumpkabooSuper Size     Ghost   Grass  335   59   66   70   41   6
784      GourgeistAverage Size     Ghost   Grass  494   65   90  122   84   6
785        GourgeistSmall Size     Ghost   Grass  494   55   85  122   99   6
786        GourgeistLarge Size     Ghost   Grass  494   75   95  122   69   6
787        GourgeistSuper Size     Ghost   Grass  494   85  100  122   54   6
788                   Bergmite       Ice     NaN  304   55   69   85   28   6
789                    Avalugg       Ice     NaN  514   95  117  184   28   6
790                     Noibat    Flying  Dragon  245   40   30   35   55   6
791                    Noivern    Flying  Dragon  535   85   70   80  123   6
792                    Xerneas     Fairy     NaN  680  126  131   95   99   6
793                    Yveltal      Dark  Flying  680  126  131   95   99   6
794           Zygarde50% Forme    Dragon  Ground  600  108  100  121   95   6
795                    Diancie      Rock   Fairy  600   50  100  150   50   6
796        DiancieMega Diancie      Rock   Fairy  700   50  160  110  110   6
797        HoopaHoopa Confined   Psychic   Ghost  600   80  110   60   70   6
798         HoopaHoopa Unbound   Psychic    Dark  680   80  160   60   80   6
799                  Volcanion      Fire   Water  600   80  110  120   70   6

[800 rows x 9 columns]

## 二.导出csv文件

In [9]:
df2.to_csv("1111.csv")